const ENV = {
  GITHUB_APP_URL: process.env.NEXT_PUBLIC_GITHUB_APP_URL,
  GITHUB_APP_NAME: process.env.NEXT_PUBLIC_GITHUB_APP_NAME,
  GITHUB_APP_CLIENT_ID: process.env.NEXT_PUBLIC_GITHUB_APP_CLIENT_ID,
  API_URL: process.env.NEXT_PUBLIC_API_URL,
  APP_BASE_URL: process.env.NEXT_PUBLIC_APP_BASE_URL,
};

export default ENV;
